In [1]:
import requests
import pandas as pd
import time
from utils import clean_text_cols, clean_datetime_cols

In [2]:
# --- 1. CONFIGURATION ---
URL = "https://gamma-api.polymarket.com/events"
TARGET_COUNT = 5000
LIMIT_PER_PAGE = 1000

In [3]:
# --- 2. FETCH & INITIAL LOAD ---

all_events = []
offset = 0

while len(all_events) < TARGET_COUNT:
    params = {
        "active": "true", 
        "closed": "false", 
        "limit": LIMIT_PER_PAGE, 
        "offset": offset,
        "order": "id",     # Sorting by ID ensures consistent pagination
        "ascending": "false"
    }
    
    print(f"Fetching events {offset} to {offset + LIMIT_PER_PAGE}...")
    response = requests.get(URL, params=params)
    
    if response.status_code != 200:
        print(f"Error: {response.status_code}")
        break
        
    data = response.json()
    
    if not data: # Break if no more data is returned
        break
        
    all_events.extend(data)
    offset += LIMIT_PER_PAGE
    
    # Small sleep to be nice to their API (Rate limit is generous, but still)
    time.sleep(0.5)

# Trim to exactly your target if needed
raw_poly_df = pd.DataFrame(all_events)
raw_poly_df.columns

Fetching events 0 to 1000...
Fetching events 1000 to 2000...
Fetching events 2000 to 3000...
Fetching events 3000 to 4000...
Fetching events 4000 to 5000...
Fetching events 5000 to 6000...
Fetching events 6000 to 7000...
Fetching events 7000 to 8000...
Fetching events 8000 to 9000...
Fetching events 9000 to 10000...

Index(['id', 'ticker', 'slug', 'title', 'description', 'resolutionSource',
       'startDate', 'creationDate', 'endDate', 'image', 'icon', 'active',
       'closed', 'archived', 'new', 'featured', 'restricted', 'liquidity',
       'createdAt', 'updatedAt', 'competitive', 'enableOrderBook',
       'liquidityClob', 'negRisk', 'commentCount', 'markets', 'series', 'tags',
       'cyom', 'showAllOutcomes', 'showMarketImages', 'enableNegRisk',
       'automaticallyActive', 'startTime', 'seriesSlug', 'negRiskAugmented',
       'pendingDeployment', 'deploying', 'requiresTranslation',
       'parentEventId', 'volume', 'openInterest', 'volume24hr', 'volume1wk',
       'volume1mo', 'volume1yr', 'negRiskMarketID', 'eventDate', 'eventWeek',
       'deployingTimestamp', 'gameId', 'eventMetadata', 'score', 'period',
       'live', 'ended', 'sortBy', 'gmpChartMode', 'estimateValue',
       'cumulativeMarkets', 'elapsed', 'finishedTimestamp', 'countryName',
       'electionType', 'cantEstimate', 'estimatedValue', 'tweetCount',
       'featuredOrder', 'eventCreators'],
      dtype='str')

In [ ]:
raw_poly_df

,id,ticker,slug,title,description,resolutionSource,startDate,creationDate,endDate,image,...,cumulativeMarkets,elapsed,finishedTimestamp,countryName,electionType,cantEstimate,estimatedValue,tweetCount,featuredOrder,eventCreators
0,318974,eth-updown-5m-1774814100,eth-updown-5m-1774814100,"Ethereum Up or Down - March 29, 3:55PM-4:00PM ET","This market will resolve to ""Up"" if the Ethere...",https://data.chain.link/streams/eth-usd,2026-03-28,2026-03-28,2026-03-29T20:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,318973,doge-updown-5m-1774814100,doge-updown-5m-1774814100,"Dogecoin Up or Down - March 29, 3:55PM-4:00PM ET","This market will resolve to ""Up"" if the Dogeco...",https://data.chain.link/streams/doge-usd,2026-03-28,2026-03-28,2026-03-29T20:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,318972,bnb-updown-5m-1774814100,bnb-updown-5m-1774814100,"BNB Up or Down - March 29, 3:55PM-4:00PM ET","This market will resolve to ""Up"" if the BNB pr...",https://data.chain.link/streams/bnb-usd,2026-03-28,2026-03-28,2026-03-29T20:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,318971,sol-updown-5m-1774814100,sol-updown-5m-1774814100,"Solana Up or Down - March 29, 3:55PM-4:00PM ET","This market will resolve to ""Up"" if the Solana...",https://data.chain.link/streams/sol-usd,2026-03-28,2026-03-28,2026-03-29T20:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,318970,xrp-updown-5m-1774814100,xrp-updown-5m-1774814100,"XRP Up or Down - March 29, 3:55PM-4:00PM ET","This market will resolve to ""Up"" if the XRP pr...",https://data.chain.link/streams/xrp-usd,2026-03-28,2026-03-28,2026-03-29T20:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,90178,will-jesus-christ-return-before-2027,will-jesus-christ-return-before-2027,Will Jesus Christ return before 2027?,"This market will resolve to ""Yes"" if The Secon...",,2025-11-25,2025-11-25,2026-12-31T00:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4996,90177,will-the-us-confirm-that-aliens-exist-before-2027,will-the-us-confirm-that-aliens-exist-before-2027,Will the US confirm that aliens exist by...?,"This market will resolve to ""Yes"" if the Presi...",,2025-11-25,2025-11-25,2026-12-31T00:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19.0,NaN
4997,90157,cbb-blkbn-eill-2025-12-01,cbb-blkbn-eill-2025-12-01,Blackburn Beavers vs. Eastern Illinois Panthers,This event is for the CBB game between Blackbu...,https://www.ncaa.com/,2025-11-25,NaN,2025-12-02T01:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,False,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4998,89603,what-price-will-uniswap-hit-before-2027,what-price-will-uniswap-hit-before-2027,What price will Uniswap hit in 2026?,What price will Uniswap hit before 2027?,,2025-11-24,2025-11-24,2027-01-01T05:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4999,89598,what-price-will-plasma-hit-before-2027,what-price-will-plasma-hit-before-2027,What price will Plasma hit in 2026?,What price will Plasma hit before 2027?,,2025-11-24,2025-11-24,2027-01-01T05:00:00Z,https://polymarket-upload.s3.us-east-2.amazona...,...,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
# --- 3. TRANSFORM: TAGS ---
# Handle nested tags first
tags_exploded = raw_poly_df[['id', 'tags']].explode('tags').dropna()
tag_labels = pd.json_normalize(tags_exploded['tags'])
tag_labels['event_id'] = tags_exploded['id'].values

# Group labels into lists and join them into a string for clean_text_cols to handle
grouped_tags = tag_labels.groupby('event_id')['label'].apply(lambda x: ', '.join(x)).reset_index()
grouped_tags.columns = ['event_id', 'tags']

In [6]:
# --- 4. TRANSFORM: EVENTS ---
event_cols = {
    'id': 'event_id',
    'title': 'event_title',
    'description': 'description',
    'startDate': 'start_date'
}

poly_events = raw_poly_df[list(event_cols.keys())].rename(columns=event_cols)
poly_events = pd.merge(poly_events, grouped_tags, on='event_id', how='left')

In [7]:
# --- 5. TRANSFORM: MARKETS ---
markets_exploded = raw_poly_df[['id', 'markets']].explode('markets').dropna()
markets_df = pd.json_normalize(markets_exploded['markets'])

# Map schema to match your Kalshi master format
market_map = {
    'id': 'market_id',
    'question': 'market_subtitle',
    'bestBid': 'yes_bid',
    'bestAsk': 'yes_ask',
    'endDateIso': 'expiration'
}

# Add event_id back for the join
markets_df['event_id'] = markets_exploded['id'].values
markets_df = markets_df.rename(columns=market_map)

# Keep only the columns we need
final_market_cols = [c for c in market_map.values() if c in markets_df.columns] + ['event_id']
markets_df = markets_df[final_market_cols].copy()

In [8]:
# --- 6. FINAL MERGE & GLOBAL CLEANING ---
master_market_df = pd.merge(markets_df, poly_events, on='event_id', how='left')
master_market_df = clean_text_cols(master_market_df)

date_cols = ['start_date', 'expiration']
master_market_df = clean_datetime_cols(master_market_df, date_cols=date_cols)

# Final formatting
master_market_df = master_market_df.sort_values(['event_id', 'market_id']).reset_index(drop=True)
master_market_df['platform'] = 'poly'
master_market_df.to_csv('data/markets/poly_markets.csv', index=False)

/Users/blakeuribe/Desktop/quasibets_testing/utils.py:68: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_dt = pd.to_datetime(df[col], utc=True, errors='coerce')

In [9]:
event_cols = ['event_id', 'event_title', 'description', 'start_date', 'tags', 'platform']

existing_cols = [c for c in event_cols if c in master_market_df.columns]
poly_events_df = master_market_df[existing_cols].drop_duplicates(subset=['event_id']).copy()

poly_events_df = clean_text_cols(poly_events_df)
poly_events_df.to_csv('data/events/poly_events.csv', index=False)
poly_events_df

,event_id,event_title,description,start_date,tags,platform
0,100079,paramount close warner bros acquisition by end...,this market will resolve to yes if paramount d...,NaN,tech finance big tech acquisitions netflix war...,poly
1,100229,close warner bros acquisition,this market will resolve according to the firs...,NaN,politics tech big tech warner bros,poly
16,100252,merab dvalishivili fight next,this market will resolve according to the next...,NaN,sports ufc,poly
56,100253,tabi fdv above one day after launch,this market will resolve to yes if the fully d...,NaN,pre market crypto tabi fdv,poly
60,100260,petr yan fight next,this market will resolve according to the next...,NaN,sports ufc,poly
...,...,...,...,...,...,...
28001,99573,netanyahu visit nyc by march 31,if israeli prime minister benjamin netanyahu v...,NaN,israel politics mamdani new york city trump ge...,poly
28002,99578,netanyahu arrested by march 31,this market will resolve to yes if israeli pri...,NaN,israel middle east courts geopolitics politics,poly
28003,99600,eu dissolves before 2027,this market will resolve to yes if the europea...,NaN,politics world geopolitics,poly
28004,99601,any country withdraws from eu before 2027,this market will resolve to yes if any europea...,NaN,politics geopolitics world,poly
28005,99714,portsmouth fc vs ipswich town fc,this event is for the upcoming efl championshi...,NaN,sports efl championship soccer games,poly

In [ ]:
import requests
import pandas as pd
import time
from utils import clean_text_cols, clean_datetime_cols

class PolymarketClient:
    def __init__(self, target_count=5000, limit_per_page=1000):
        self.base_url = "https://gamma-api.polymarket.com/events"
        self.target_count = target_count
        self.limit_per_page = limit_per_page
        self.raw_data = None
        self.master_df = None

    def fetch_events(self):
        """Fetches raw event data from the Gamma API with pagination."""
        all_events = []
        offset = 0

        while len(all_events) < self.target_count:
            params = {
                "active": "true",
                "closed": "false",
                "limit": self.limit_per_page,
                "offset": offset,
                "order": "id",
                "ascending": "false"
            }
            
            print(f"Fetching Polymarket events {offset} to {offset + self.limit_per_page}...")
            try:
                response = requests.get(self.base_url, params=params)
                response.raise_for_status()
                data = response.json()
                
                if not data:
                    break
                    
                all_events.extend(data)
                offset += self.limit_per_page
                time.sleep(0.5)
            except requests.exceptions.RequestException as e:
                print(f"Request failed: {e}")
                break

        self.raw_data = pd.DataFrame(all_events)
        return self.raw_data

    def _process_tags(self):
        """Internal helper to flatten and group tags."""
        tags_exploded = self.raw_data[['id', 'tags']].explode('tags').dropna()
        tag_labels = pd.json_normalize(tags_exploded['tags'])
        tag_labels['event_id'] = tags_exploded['id'].values
        
        grouped_tags = tag_labels.groupby('event_id')['label'].apply(lambda x: ', '.join(x)).reset_index()
        grouped_tags.columns = ['event_id', 'tags']
        return grouped_tags

    def transform_data(self):
        """Processes raw JSON into market and event DataFrames."""
        if self.raw_data is None or self.raw_data.empty:
            raise ValueError("No data found. Run fetch_events() first.")

        # 1. Process Tags & Events
        grouped_tags = self._process_tags()
        event_cols_map = {'id': 'event_id', 'title': 'event_title', 'description': 'description', 'startDate': 'start_date'}
        
        poly_events = self.raw_data[list(event_cols_map.keys())].rename(columns=event_cols_map)
        poly_events = pd.merge(poly_events, grouped_tags, on='event_id', how='left')

        # 2. Process Markets
        markets_exploded = self.raw_data[['id', 'markets']].explode('markets').dropna()
        markets_df = pd.json_normalize(markets_exploded['markets'])
        
        market_map = {
            'id': 'market_id',
            'question': 'market_subtitle',
            'bestBid': 'yes_bid',
            'bestAsk': 'yes_ask',
            'endDateIso': 'expiration'
        }
        
        markets_df['event_id'] = markets_exploded['id'].values
        markets_df = markets_df.rename(columns=market_map)
        
        # Filter for schema-compliant columns
        final_cols = [c for c in market_map.values() if c in markets_df.columns] + ['event_id']
        markets_df = markets_df[final_cols].copy()

        # 3. Final Merge and Cleaning
        self.master_df = pd.merge(markets_df, poly_events, on='event_id', how='left')
        self.master_df = clean_text_cols(self.master_df)
        self.master_df = clean_datetime_cols(self.master_df, date_cols=['start_date', 'expiration'])
        
        self.master_df['platform'] = 'poly'
        self.master_df = self.master_df.sort_values(['event_id', 'market_id']).reset_index(drop=True)
        
        return self.master_df

    def get_separated_dfs(self):
        """Returns both the full markets DF and the unique events DF."""
        if self.master_df is None:
            self.transform_data()
            
        # event_cols = ['event_id', 'event_title', 'description', 'start_date', 'tags', 'platform'] # need to fix start date
        event_cols = ['event_id', 'event_title', 'description', 'tags', 'platform']
        
        existing_cols = [c for c in event_cols if c in self.master_df.columns]
        
        events_df = self.master_df[existing_cols].drop_duplicates(subset=['event_id']).copy()
        events_df = clean_text_cols(events_df)
        
        return self.master_df, events_df

# --- Usage Example ---
client = PolymarketClient()
client.fetch_events()
markets_df, events_df = client.get_separated_dfs()

# Save results
# markets_df.to_csv('data/markets/poly_markets.csv', index=False)
# events_df.to_csv('data/events/poly_events.csv', index=False)

print("Transformation complete. Events Sample:")
print(events_df.head())

Fetching Polymarket events 0 to 1000...
Fetching Polymarket events 1000 to 2000...
Fetching Polymarket events 2000 to 3000...
Fetching Polymarket events 3000 to 4000...
Fetching Polymarket events 4000 to 5000...
Fetching Polymarket events 5000 to 6000...
Fetching Polymarket events 6000 to 7000...
Fetching Polymarket events 7000 to 8000...
Fetching Polymarket events 8000 to 9000...
Fetching Polymarket events 9000 to 10000...

/Users/blakeuribe/Desktop/quasibets_testing/utils.py:68: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  temp_dt = pd.to_datetime(df[col], utc=True, errors='coerce')

Transformation complete. Events Sample:
   event_id                                        event_title  \
0    100079  paramount close warner bros acquisition by end...
1    100229                      close warner bros acquisition
16   100252                      merab dvalishivili fight next
56   100253                tabi fdv above one day after launch
60   100260                                petr yan fight next

                                          description start_date  \
0   this market will resolve to yes if paramount d...        NaN
1   this market will resolve according to the firs...        NaN
16  this market will resolve according to the next...        NaN
56  this market will resolve to yes if the fully d...        NaN
60  this market will resolve according to the next...        NaN

                                                 tags platform
0   tech finance big tech acquisitions netflix war...     poly
1                  politics tech big tech warner bros     poly
16                                         sports ufc     poly
56                         pre market crypto tabi fdv     poly
60                                         sports ufc     poly

In [11]:
events_df

,event_id,event_title,description,start_date,tags,platform
0,100079,paramount close warner bros acquisition by end...,this market will resolve to yes if paramount d...,NaN,tech finance big tech acquisitions netflix war...,poly
1,100229,close warner bros acquisition,this market will resolve according to the firs...,NaN,politics tech big tech warner bros,poly
16,100252,merab dvalishivili fight next,this market will resolve according to the next...,NaN,sports ufc,poly
56,100253,tabi fdv above one day after launch,this market will resolve to yes if the fully d...,NaN,pre market crypto tabi fdv,poly
60,100260,petr yan fight next,this market will resolve according to the next...,NaN,sports ufc,poly
...,...,...,...,...,...,...
28001,99573,netanyahu visit nyc by march 31,if israeli prime minister benjamin netanyahu v...,NaN,israel politics mamdani new york city trump ge...,poly
28002,99578,netanyahu arrested by march 31,this market will resolve to yes if israeli pri...,NaN,israel middle east courts geopolitics politics,poly
28003,99600,eu dissolves before 2027,this market will resolve to yes if the europea...,NaN,politics world geopolitics,poly
28004,99601,any country withdraws from eu before 2027,this market will resolve to yes if any europea...,NaN,politics geopolitics world,poly
28005,99714,portsmouth fc vs ipswich town fc,this event is for the upcoming efl championshi...,NaN,sports efl championship soccer games,poly